from opencsp.envmanagers.AWSEnvManager.AWSEnvManager import AWSEnvManager
from opencsp.envmanagers.DefaultEnvManager.DefaultEnvManager import DefaultEnvManager
from opencsp.envmanagers.DefaultEnvManager.DefaultEnvManagerAppVirtualBox import DefaultEnvManagerAppVirtualBox
from opencsp.envmanagers.LIPEnvManager.LIPEnvManager import LIPEnvManager
from opencsp.envmanagers.LIPEnvManager.LIPEnvManagerAppImageRegistrationAnts import LIPEnvManagerAppImageRegistrationAnts
from opencsp.envmanagers.LIPEnvManager.LIPEnvManagerAppImageRegistrationCmtk322 import LIPEnvManagerAppImageRegistrationCmtk322
from opencsp.envmanagers.LIPEnvManager.LIPEnvManagerAppSpikeSorter import LIPEnvManagerAppSpikeSorter
from opencsp.envmanagers.LIPHPCEnvManager.LIPHPCEnvManager import LIPHPCEnvManager
from opencsp.envmanagers.LIPHPCEnvManager.LIPHPCEnvManagerAppImageRegistrationAnts import LIPHPCEnvManagerAppImageRegistrationAnts
from opencsp.envmanagers.LIPHPCEnvManager.LIPHPCEnvManagerAppSpikeSorter import LIPHPCEnvManagerAppSpikeSorter
from opencsp.envmanagers.LIPHPCEnvManager.LIPHPCEnvManagerAppThunder import LIPHPCEnvManagerAppThunder
from opencsp.envmanagers.RenartSpikeEnvManager.RenartSpikeEnvManager import RenartSpikeEnvManager

ENVIRONMENTS = {}
ENVIRONMENTS['AWSEnvManager'] = AWSEnvManager()
ENVIRONMENTS['DefaultEnvManager'] = DefaultEnvManager()
ENVIRONMENTS['DefaultEnvManagerAppVirtualBox'] = DefaultEnvManagerAppVirtualBox()
ENVIRONMENTS['LIPEnvManager'] = LIPEnvManager()
ENVIRONMENTS['LIPEnvManagerAppImageRegistrationAnts'] = LIPEnvManagerAppImageRegistrationAnts()
ENVIRONMENTS['LIPEnvManagerAppImageRegistrationCmtk322'] = LIPEnvManagerAppImageRegistrationCmtk322()
ENVIRONMENTS['LIPEnvManagerAppSpikeSorter'] = LIPEnvManagerAppSpikeSorter()
ENVIRONMENTS['LIPHPCEnvManager'] = LIPHPCEnvManager()
ENVIRONMENTS['LIPHPCEnvManagerAppImageRegistrationAnts'] = LIPHPCEnvManagerAppImageRegistrationAnts()
ENVIRONMENTS['LIPHPCEnvManagerAppSpikeSorter'] = LIPHPCEnvManagerAppSpikeSorter()
ENVIRONMENTS['LIPHPCEnvManagerAppThunder'] = LIPHPCEnvManagerAppThunder()
ENVIRONMENTS['RenartSpikeEnvManager'] = RenartSpikeEnvManager()
