ORQUESTRA_HOME_FUNCTION 	= None

ORQUESTRA_TOP 		  = 0
ORQUESTRA_BOTTOM 	  = 1
ORQUESTRA_WINDOW 	  = 2
ORQUESTRA_JSON 		  = 3
ORQUESTRA_NEW_WINDOW  = 4
ORQUESTRA_NEW_TAB 	  = 5
ORQUESTRA_HOME 		  = 0
ORQUESTRA_APPEND_HOME = 6
ORQUESTRA_NONE 		  = 100