ORQUESTRA_HOME_FUNCTION 	= None

ORQUESTRA_HOME 		   = 0
ORQUESTRA_NEW_TAB 	   = 1
ORQUESTRA_NEW_WINDOW   = 2
ORQUESTRA_APPEND_HOME  = 3
ORQUESTRA_HOME_FULL    = 4
ORQUESTRA_NEW_TAB_FULL = 5


ORQUESTRA_REQUIREAUTH = False

ORQUESTRA_SHOW_NO_MODULE_EXCEPTION = True

ORQUESTRA_TITLE = ''

